database: &database
  adapter: postgresql
  host: localhost
  port: 5432
  timeout: 5000
  schema_search_path: "sequent_schema, view_schema"
  username: <%= ENV["DB_USER"]%>
  password: <%= ENV["DB_PASSWORD"]%>


development:
  <<: *database
  pool: 5
  database: blog_development

test:
  <<: *database
  pool: 5
  database: blog_test
